export const LIST_TVSHOWS = 'tv-shows'
export const LIST_TVEPISODES = 'tv-episodes'
export const REF_SHOWS = 'ref-shows'
export const REF_CHAPTERS = 'ref-chapters'
export const GET_NOTSEEN = 'notseen'
export const LOGIN_USER = 'login-user'
export const MODAL_OPTIONS_ISOPEN = 'is-options-open'
export const MODAL_DETAILS_ISOPEN = 'is-details-open'
export const MODAL_SHOW = 'login-user'
 